milestone-one / desktop-version
alexander16108/Portfolio pull request #1
Opened 2021-06-10 21:20 UTC by alexander16108

- add linter dependencies
- add HTML and CSS files
- check for linter errors
- create a PR 
- awaiting CR

2021-06-10 21:36 UTC, Shaher-11 requested changes
Hello @alexander16108  

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] You need to make sure that your desktop version looks like the one in the Figma  [Template.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) 

#### Here is what the project looks like now

![wrong3](https://user-images.githubusercontent.com/58376020/121600301-90271780-ca44-11eb-9439-e78ad55c1e44.png)
![wrong2](https://user-images.githubusercontent.com/58376020/121600312-92897180-ca44-11eb-80c8-5534e7dcf0fc.png)
![wrong1](https://user-images.githubusercontent.com/58376020/121600322-94ebcb80-ca44-11eb-86be-570e8f7ad3c7.png)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-06-11 10:05 UTC, rloterh requested changes
# Changes Required! ♻️

Hi @alexander16108 👋 👋, I'm Robert, your 2nd reviewer for this PR.

I must commend you for the nice work done👏.  You nailed almost all of the specifications of this project right. You did a great job by implementing most changes recommended by the previous reviewer(s). Kindly check the below comments for the necessary changes we can implement to make our application more robust.

## Good points 👍
No Linters errors ✔️
Good use of HTML semantics ✔️


## Aspects to improve ♻️

_Check the comment(s) under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**

- [OPTIONAL] The **Author** section of our ReadMe lacks enough info about the author(s). Let's improve this aspect by adding additional profile links such as LinkedIn, Twitter, and Github, and ensure that the highlighted profile has links that navigate to the corresponding profile URL when clicked.


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 10:05 UTC, rloterh commented on index.html
> +    </nav>
- [ ] Your layout looks great! We however want our design to look like the design template provided in the Figma as much as possible. We actually want our design to have appropriate margins at the **top, bottom, left, and or right** proportionally. 

Here is your design:

![shot1](https://user-images.githubusercontent.com/12745474/121665901-9c40c280-caa0-11eb-8059-1f720a217b50.jpeg)

You can see we don't have enough margin around the logo area and the left margin.

Check out the Figma design template :
![shot2](https://user-images.githubusercontent.com/12745474/121666743-7f58bf00-caa1-11eb-9dd3-b15e1b59130c.jpeg)

You can see that we have enough margin flow around the top area. Let's unsure to add appropriate margins at the top and left side.

2021-06-11 12:02 UTC, ElijahTobs approved these changes
# STATUS: APPROVED 🎉 🥇 
## Hi Team, 

Good job making the changes required by the previous Code Reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional Changes 👌
_Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better._

- Henceforth, always capitalize your commit messages



_Check for changes marked as Optional in the inline comments below._


_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

_Reviewed by_: __**Elijah Ayandokun**__

2021-06-11 12:02 UTC, ElijahTobs commented on index.html
> +        </ul>
- [ ] _[Optional]_ The font-weight of the logo should be the same as that of the nav items.
- [ ] _[Optional]_ You should capitalize the text `portfolio`.

2021-06-11 12:02 UTC, ElijahTobs commented on README.md
> +https://alexander16108.github.io/destop-version/
- [ ] _[Optional]_ The live demo link isn't working. It takes forever to load and eventually does not come up with anything
- [ ] _[Optional]_ Your README would look nicer if you add a screenshot of your project.

2021-06-11 12:42 UTC, merged